language: go
go:
  - 1.4
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -u github.com/kr/godep
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet
  - godep get
  - godep go build -v ./...
script:
  - godep go test -v ./...
  - test -z "$(go fmt ./...)"
  - golint ./...
  - test -z "$(golint ./...)"
  - go vet ./...
  - bats test
