language: go
go:
  - 1.4
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -u github.com/kr/godep
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet
  - godep get
  - godep go build -v ./...
script:
  - godep go test -v ./...
  - test -z "$(go fmt ./...)"
  - golint ./...
  - go vet ./...
