environment:
  nodejs_version: "7"
cache:
  #- %LOCALAPPDATA%\\Yarn
  - node_modules -> package.json
  - yarn

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%LOCALAPPDATA%\Yarn\config\global\node_modules\.bin;%PATH%
  - yarn global add yarn
  - yarn
  - yarn run prepare
  - git submodule sync
  - git submodule update --init --recursive --remote
test_script:
  - ./node_modules/.bin/jest -i

build: off
