---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine:latest
stages:
  build:
    workDir: ~/cli-engine
    environment:
      - CIRCLE_PROJECT_USERNAME: heroku
      - CIRCLE_PROJECT_REPONAME: cli-engine
      - HEROKU_DEBUG: 1
    steps:
      - type: checkout
      - type: cache-restore
        key: cli-engine-{{checksum "package.json"}}
      - type: shell
        command: |
          set -exu

          # setup yarn
          yarn --prefer-offline --pure-lockfile
          cd node_modules/cli-engine-command && yarn && cd ~/cli-engine
          cd example && yarn add --prefer-offline heroku/cli-engine#$CIRCLE_SHA1 && cd ~/cli-engine
          cd example/node_modules/cli-engine-command && yarn && cd ~/cli-engine

          # test project
          JEST_JUNIT_OUTPUT=/tmp/test-results/jest/junit.xml ./node_modules/.bin/jest --coverage --testResultsProcessor jest-junit
          ./node_modules/.bin/flow check
          ./node_modules/.bin/standard
          bash <(curl -s https://codecov.io/bash)
          ./bin/run version

          # test/build example project
          cd example
          ./bin/run version
          ./bin/run help
          ./bin/run cli:test
          yarn run build linux-x64 beta
          cd ..

          # show files in npm pack
          npm pack
          tar xvzf cli-engine*.tgz
          rm -rf package
          mkdir -p /tmp/artifacts
          mv cli-engine*.tgz /tmp/artifacts/cli-engine.tgz
      - type: test-results-store
        path: /tmp/test-results
      - type: artifacts-store
        path: /tmp/artifacts
        destination: build
      - type: cache-save
        key: cli-engine-{{checksum "package.json"}}
        paths:
          - /usr/local/share/.cache/yarn
  deploy:
    workDir: ~/cli-engine
    steps:
      - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -exu
          if [ "${CIRCLE_BRANCH}" == "master" ];
            cd example && npm run build 
          fi
