---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine@sha256:090e7e327787303491f27482f021b9fbcfeac1d379a20769c7524c1c53b68c88
stages:
  build:
    workDir: ~/cli-engine
    environment:
      - CIRCLE_PROJECT_USERNAME: heroku
      - CIRCLE_PROJECT_REPONAME: cli-engine
    steps:
      - type: checkout
      - type: cache-restore
        key: cli-engine-{{checksum "package.json"}}
      - type: shell
        command: |
          set -exu

          git submodule sync
          git submodule update --init --recursive --remote

          # setup yarn
          yarn
          cd ~/cli-engine/example
          yarn
          yarn add heroku/cli-engine#$CIRCLE_SHA1
          cd ~/cli-engine/example/node_modules/cli-engine
          yarn
          npm run prepare

          # test project
          cd ~/cli-engine
          ./node_modules/.bin/jest --coverage
          ./node_modules/.bin/flow check
          ./node_modules/.bin/standard
          bash <(curl -s https://codecov.io/bash)
          ./bin/run version

          # test/build example project
          cd ~/cli-engine/example
          ./bin/run version
          ./bin/run help
          ./bin/run cli:test
          yarn run build linux-x64 beta

          # show files in npm pack
          cd ~/cli-engine
          npm pack
          tar xvzf cli-engine*.tgz
          rm -rf package
          mkdir -p /tmp/artifacts
          mv cli-engine*.tgz /tmp/artifacts/cli-engine.tgz
      - type: artifacts-store
        path: /tmp/artifacts
        destination: build
      - type: cache-save
        key: cli-engine-{{checksum "package.json"}}
        paths:
          - /usr/local/share/.cache/yarn
          - ~/cli-engine/node_modules
          - ~/cli-engine/example/node_modules
      - type: deploy
        shell: /bin/bash
        command: |
          set -exu
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd example && npm run release beta
          fi
